//
// Created by ThinkPad41 on 10/10/2021.
//

#ifndef BEYOND_RGB_BACKEND_COLORMANGAGEDCALABRATOR_H
#define BEYOND_RGB_BACKEND_COLORMANGAGEDCALABRATOR_H


class ColorMangagedCalabrator {

};


#endif //BEYOND_RGB_BACKEND_COLORMANGAGEDCALABRATOR_H
